/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check


/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  anderesoftware: [{
    type: 'autogenerated', 
    dirName: 'anderesoftware'
  }], 
  byod: [{
    type: 'autogenerated', 
    dirName: 'byod'
  }], 
  dokumentation: [{
    type: 'autogenerated', 
    dirName: 'dokumentation'
  }], 
  infra: [{
    type: 'autogenerated', 
    dirName: 'infra'
  }], 
  internet: [{
    type: 'autogenerated', 
    dirName: 'internet'
  }], 
  microsoft365: [{
    type: 'autogenerated', 
    dirName: 'microsoft365'
  }], 
  praesentation: [{
    type: 'autogenerated', 
    dirName: 'praesentation'
  }], 
  sicherheit: [{
    type: 'autogenerated', 
    dirName: 'sicherheit'
  }], 
  tabellenkalkulation: [{
    type: 'autogenerated', 
    dirName: 'tabellenkalkulation'
  }],
  textverarbeitung: [{
    type: 'autogenerated', 
    dirName: 'textverarbeitung'
  }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
